version: '3.7'

services:
  aws-for-fluent-bit-custom:
    build: ./aws-for-fluent-bit-custom
    command: "/fluent-bit/bin/fluent-bit -c /fluent-bit/conf/local_stdout_test.conf"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  backend-flask:
    build: ./backend-flask/flask
    ports:
      - "5000:5000"
    depends_on:
      - aws-for-fluent-bit-custom
    logging:
      driver: fluentd
    restart: always
    environment:
      - VERSION=V1
    healthcheck:
          test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:5000"]
          interval: 30s
          timeout: 5s
          retries: 5
          start_period: 30s

  backend-flask-nginx-proxy:
    build: ./backend-flask/nginx
    ports:
      - "80:80"
    depends_on:
      - aws-for-fluent-bit-custom
      - backend-flask
    logging:
      driver: fluentd
    environment:
    - BACKEND_FLASK_HOST=backend-flask
    - BACKEND_FLASK_PORT=5000
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  
  frontend-express:
    depends_on:
      - aws-for-fluent-bit-custom
      - backend-flask-nginx-proxy
    logging:
      driver: fluentd
    build: ./frontend-express
    restart: always
    ports:
      - "8080:8080"
    restart: always
    environment:
    - BACKEND_SERVICE=http://backend-flask-nginx-proxy/backend
    - PORT=8080

